plugins {
	id 'java'
}

jar.enabled = false

subprojects {
	group = 'com.slcube'
	version = '0.0.1-SNAPSHOT'

	java {
		toolchain {
			languageVersion.set(JavaLanguageVersion.of(17))
		}
	}

	apply plugin: 'java'
	apply plugin: 'java-library'

	repositories {
		mavenCentral()
	}

	dependencies {
		compileOnly 'org.projectlombok:lombok:1.18.24'
		annotationProcessor 'org.projectlombok:lombok:1.18.24'
	}

	tasks.named('test') {
		useJUnitPlatform()
	}

	tasks.named('build') {
		dependsOn(':module-boot:bootJar')
	}
}