pluginManagement {
    repositories {
        maven { url 'https://repo.spring.io/milestone' }
        maven { url 'https://repo.spring.io/snapshot' }
        gradlePluginPortal()
    }
}

rootProject.name = 'lostart.discord.bot'

include 'module-domain'
include 'module-app'
include 'module-infra'

